export type BootstrapElement =
  | 'accordion'
  | 'accordion-body'
  | 'accordion-button'
  | 'accordion-collapse'
  | 'accordion-header'
  | 'accordion-item'
  | 'alert'
  | 'alert-heading'
  | 'alert-link'
  | 'badge'
  | 'breadcrumb'
  | 'breadcrumb-item'
  | 'btn'
  | 'btn-group'
  | 'btn-toolbar'
  | 'card'
  | 'card-body'
  | 'card-footer'
  | 'card-group'
  | 'card-header'
  | 'card-img'
  | 'card-img-overlay'
  | 'card-link'
  | 'card-subtitle'
  | 'card-text'
  | 'card-title'
  | 'carousel'
  | 'carousel-caption'
  | 'carousel-control'
  | 'carousel-control-icon'
  | 'carousel-indicator'
  | 'carousel-indicators'
  | 'carousel-inner'
  | 'carousel-item'
  | 'col'
  | 'collapse'
  | 'container'
  | 'dropdown'
  | 'dropdown-divider'
  | 'dropdown-header'
  | 'dropdown-item'
  | 'dropdown-menu'
  | 'dropdown-toggle'
  | 'form-check'
  | 'form-check-input'
  | 'form-check-label'
  | 'form-control'
  | 'form-label'
  | 'form-range'
  | 'form-select'
  | 'form-text'
  | 'input-group'
  | 'input-group-text'
  | 'list-group'
  | 'list-group-item'
  | 'modal'
  | 'modal-body'
  | 'modal-content'
  | 'modal-dialog'
  | 'modal-footer'
  | 'modal-header'
  | 'modal-title'
  | 'nav'
  | 'nav-item'
  | 'nav-link'
  | 'navbar'
  | 'navbar-brand'
  | 'navbar-collapse'
  | 'navbar-nav'
  | 'navbar-text'
  | 'navbar-toggler-icon'
  | 'offcanvas'
  | 'offcanvas-body'
  | 'offcanvas-header'
  | 'offcanvas-title'
  | 'page-item'
  | 'page-link'
  | 'pagination'
  | 'placeholder'
  | 'placeholder-animation'
  | 'popover'
  | 'popover-body'
  | 'popover-header'
  | 'progress'
  | 'progress-bar'
  | 'progress-stacked'
  | 'spinner'
  | 'toast'
  | 'toast-body'
  | 'toast-container'
  | 'toast-header'
  | 'tooltip'
  | 'tooltip-arrow'
  | 'tooltip-inner'
  | 'table'
  | 'table-responsive'

/** Theme included in Bootstrap by default */
export type BootstrapTheme = 'light' | 'dark'

/** Breakpoint included in Bootstrap by default */
export type BootstrapDefaultBreakpoint = 'sm' | 'md' | 'lg' | 'xl' | 'xxl'

/** Theme color name included in Bootstrap by default */
export type BootstrapThemeColor =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'info'
  | 'warning'
  | 'danger'
  | 'light'
  | 'dark'

/** Theme subtle color name included in Bootstrap by default */
export type BootstrapThemeColorSubtle =
  | 'primary-subtle'
  | 'secondary-subtle'
  | 'success-subtle'
  | 'danger-subtle'
  | 'warning-subtle'
  | 'info-subtle'
  | 'light-subtle'
  | 'dark-subtle'

/** Button colors included in Bootstrap by default */
export type BootstrapButtonColor = BootstrapThemeColor | 'close' | 'link'

/** Button sizes included in Bootstrap by default */
export type BootstrapButtonSize = 'sm' | 'lg'

/** Text colors included in Bootstrap by default */
export type BootstrapTextColor =
  | BootstrapThemeColor
  | 'primary-emphasis'
  | 'secondary-emphasis'
  | 'success-emphasis'
  | 'info-emphasis'
  | 'warning-emphasis'
  | 'danger-emphasis'
  | 'light-emphasis'
  | 'dark-emphasis'
  | 'bg-primary'
  | 'bg-secondary'
  | 'bg-success'
  | 'bg-info'
  | 'bg-warning'
  | 'bg-danger'
  | 'bg-light'
  | 'bg-dark'
  | 'black'
  | 'white'
  | 'body'
  | 'body-secondary'
  | 'body-tertiary'
  | 'body-emphasis'
  | 'reset'
