[[plugins]]
package = "@resoc/netlify-plugin-social-image"
  [plugins.inputs]
  templates_dir = "apps/jack-barry-onl/resoc-template"
  slug_to_image_data_mapping_file = "apps/jack-barry-onl/resoc-image-data.json"
  open_graph_base_path = "/social-images"
