[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
  environment = { NODE_VERSION = "16.14.2" }
  command = "cd ../.. && npm ci && npx nx run jack-barry-onl:build:production"
  publish = "../../dist/apps/jack-barry-onl/.next"
