// This file is generated by Slice Machine. Update with care!

import BlogPostSection from './BlogPostSection'
import CodeBlock from './CodeBlock'
import RichTextCard from './RichTextCard'

export { BlogPostSection, CodeBlock, RichTextCard }

export const components = {
  blog_post_section: BlogPostSection,
  code_block: CodeBlock,
  rich_text_card: RichTextCard
}
