// This file is generated by Slice Machine. Update with care!

import RichTextCard from './RichTextCard'
import StandardRichTextBlock from './StandardRichTextBlock'

export { RichTextCard, StandardRichTextBlock }

export const components = {
  rich_text_card: RichTextCard,
  standard_rich_text_block: StandardRichTextBlock
}
