name: CI
on:
  push:
    branches:
      - dev
      - main
  pull_request: null
  workflow_dispatch: null
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set SHAs for Nx Affected Commands
        id: nx_shas
        uses: nrwl/nx-set-shas@v2
      - name: Setup Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm ci --verbose
      - name: Build Affected
        run: npx nx affected:build
      - name: Test Affected
        run: npx nx affected:test
