name: Deploy Jack.Barry.onl

on:
  workflow_dispatch: null

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: 'npm'
      - run: npm ci
      - name: Publish using Netlify CLI
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          PRISMIC_ACCESS_TOKEN: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          SITE_ID_JACK_BARRY_ONL: ${{ secrets.SITE_ID_JACK_BARRY_ONL }}
        run: npx nx run jack-barry-onl:deploy
